import http from 'k6/http';
import { check } from 'k6';
import { uuidv4 } from 'https://jslib.k6.io/k6-utils/1.2.0/index.js';
import { weightedSleep } from '../utils/weightedSleep.js';

export const options = {
  stages: [
    { duration: '10s', target: 1 }, // Scale over 5 mins.
    // { duration: '300s', target: 30 }, // Scale over 5 mins.
    // { duration: '600s', target: 30 }, // Stay for 10 mins.
  ],
};

export const postGlobalPromo = (anonId, promo) => {
  const body = JSON.stringify({
    promo: promo,
    cart: [],
    identity: {
      anonId: anonId,
    },
  });

  const response = http.post(
    'https://rev-api-proxy.shoesforcrews.com/api/globalPromo',
    body,
    {
      headers: {
        'Content-Type': 'application/json',
      },
    }
  );

  check(response, {
    'is status 200': (r) => r.status === 200,
  });

  const calculate = http.post(
    'https://rev-api-proxy.shoesforcrews.com/api/promo/calculate',
    JSON.stringify(testData),
    {
      headers: {
        'Content-Type': 'application/json',
      },
    }
  );

  check(calculate, {
    'is status 200': (r) => r.status === 200,
  });

  //   weightedSleep(5, response);
};

export default function () {
  const anonId = 'load_test_' + uuidv4();
  postGlobalPromo(anonId, 'BKF635');
}

const testData = {
  products: [
    {
      uniqueId: '22201',
      title: 'Gia',
      highestFinalPrice: 84.98,
      brand: ['Shoes For Crews'],
      modelnumber: '22201',
      catlevel3Name: 'New Non-Slip Styles!',
      imageUrl: [
        'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
      ],
      brand_attribute: 'Shoes For Crews',
      color: ['Black'],
      gender: ['Women'],
      new_item: 'true',
      style: ['22201'],
      wide: 'false',
      extraWide: 'false',
      gender_code: 'W',
      womens_size_difference: '0.0',
      sizesApply: 'shoes',
      businessSelectPrice: '79.98',
      autosuggest: 'Gia',
      variantTotal: 12,
      score: 0.9857124,
      variantCount: 12,
      variants: [
        {
          id: '6226f13cd1b42900179c5eab',
          sku: '22201-10',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 411,
          size: ['10'],
          sizeText: '10 (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eac',
          sku: '22201-11',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 835,
          size: ['11'],
          sizeText: '11 (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5ead',
          sku: '22201-5',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 135,
          size: ['5'],
          sizeText: '5 (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eae',
          sku: '22201-55',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 303,
          size: ['5.5'],
          sizeText: '5½ (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eaf',
          sku: '22201-6',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 104,
          size: ['6'],
          sizeText: '6 (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eb0',
          sku: '22201-65',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 1466,
          size: ['6.5'],
          sizeText: '6½ (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eb1',
          sku: '22201-7',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 550,
          size: ['7'],
          sizeText: '7 (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eb2',
          sku: '22201-75',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 1978,
          size: ['7.5'],
          sizeText: '7½ (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eb3',
          sku: '22201-8',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 1504,
          size: ['8'],
          sizeText: '8 (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eb4',
          sku: '22201-85',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 2376,
          size: ['8.5'],
          sizeText: '8½ (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eb5',
          sku: '22201-9',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 1598,
          size: ['9'],
          sizeText: '9 (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
        {
          id: '6226f13cd1b42900179c5eb6',
          sku: '22201-95',
          ourPrice: 84.98,
          finalPrice: 84.98,
          inventory: 1776,
          size: ['9.5'],
          sizeText: '9½ (Med)',
          title: 'Gia',
          highestFinalPrice: 84.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22201',
          catlevel3Name: 'New Non-Slip Styles!',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22201/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'true',
          style: ['22201'],
          wide: 'false',
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '79.98',
          autosuggest: 'Gia',
          score: 0.5,
        },
      ],
      prank: '1',
      finalPrice: 84.98,
    },
    {
      uniqueId: '22146',
      title: 'Everlight',
      highestFinalPrice: 59.98,
      brand: ['Shoes For Crews'],
      modelnumber: '22146',
      catlevel3Name: 'Athletic',
      imageUrl: [
        'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
      ],
      brand_attribute: 'Shoes For Crews',
      color: ['Black'],
      gender: ['Women'],
      new_item: 'false',
      style: ['22146'],
      extraWide: 'false',
      gender_code: 'W',
      womens_size_difference: '0.0',
      sizesApply: 'shoes',
      businessSelectPrice: '54.98',
      autosuggest: 'Everlight',
      variantTotal: 24,
      score: 0.911307,
      variantCount: 21,
      variants: [
        {
          id: '60a444b0eee8740010717ab9',
          sku: '22146-55',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 470,
          size: ['5.5'],
          wide: 'false',
          sizeText: '5½ (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717abc',
          sku: '22146-7',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 1988,
          size: ['7'],
          wide: 'false',
          sizeText: '7 (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717abe',
          sku: '22146-8',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 4299,
          size: ['8'],
          wide: 'false',
          sizeText: '8 (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717ac0',
          sku: '22146-9',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 3998,
          size: ['9'],
          wide: 'false',
          sizeText: '9 (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717aba',
          sku: '22146-6',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 740,
          size: ['6'],
          wide: 'false',
          sizeText: '6 (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717ab7',
          sku: '22146-11',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 938,
          size: ['11'],
          wide: 'false',
          sizeText: '11 (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717ac1',
          sku: '22146-95',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 3671,
          size: ['9.5'],
          wide: 'false',
          sizeText: '9½ (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717abd',
          sku: '22146-75',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 2429,
          size: ['7.5'],
          wide: 'false',
          sizeText: '7½ (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717abf',
          sku: '22146-85',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 4276,
          size: ['8.5'],
          wide: 'false',
          sizeText: '8½ (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717ab6',
          sku: '22146-10',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 2553,
          size: ['10'],
          wide: 'false',
          sizeText: '10 (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
        {
          id: '60a444b0eee8740010717ab8',
          sku: '22146-5',
          ourPrice: 59.98,
          finalPrice: 59.98,
          inventory: 258,
          size: ['5'],
          wide: 'false',
          sizeText: '5 (Med)',
          title: 'Everlight',
          highestFinalPrice: 59.98,
          brand: ['Shoes For Crews'],
          modelnumber: '22146',
          catlevel3Name: 'Athletic',
          imageUrl: [
            'https://www.shoesforcrews.com/shared-imgs/productimages/us_en/22146/0000-1024.jpg',
          ],
          brand_attribute: 'Shoes For Crews',
          color: ['Black'],
          gender: ['Women'],
          new_item: 'false',
          style: ['22146'],
          extraWide: 'false',
          gender_code: 'W',
          womens_size_difference: '0.0',
          sizesApply: 'shoes',
          businessSelectPrice: '54.98',
          autosuggest: 'Everlight',
          score: 0.5,
        },
      ],
    },
  ],
  promo: 'BKF635',
  isBusinessSelect: false,
};
